# Project
version=1.3.0
group=einstein
java_version=21

# Common
minecraft_version=1.21.11
max_minecraft_version=26.1
neo_form_version=1.21.11-20251209.172050
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric
fabric_version=0.18.4
fabric_api_version=0.140.2+1.21.11

# NeoForge
neoforge_version=21.11.17-beta
neoforge_loader_version_range=[4,)

#Mod options
mod_name=WhitePumpkins
mod_author=MincraftEinstein
mod_id=white_pumpkins
description=Adds Minecraft Story Mode inspired white pumpkins that will generate in the pale garden. Made for SpookyJam 2024

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
