modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "All rights reserved"
issueTrackerURL = "https://github.com/MincraftEinstein/WhitePumpkins/issues"

[[mods]]
    modId = "white_pumpkins"
    version = "${version}"
    displayName = "${mod_name}"
    #updateJSONURL = "https://change.me.example.invalid/updates.json"
    displayURL = "https://curseforge.com/minecraft/mc-mods/white-pumpkins"
    logoFile = "pack.png"
    credits = ""
    authors = "${mod_author}"
    description = '''${description}'''

[[accessTransformers]]
    file = "META-INF/accesstransformer.cfg"

[[mixins]]
    config = "${mod_id}.mixins.json"

[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"

[[dependencies.white_pumpkins]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.white_pumpkins]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version}, ${max_minecraft_version})"
    ordering = "NONE"
    side = "BOTH"
